import { transformSync } from "esbuild";
import { readdirSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
const cwd = process.cwd();
const dist = "arcaea-toolbelt";
const children = readdirSync(resolve(cwd, dist));
const js = children.find((f) => f.endsWith(".js"));
const bundle = resolve(cwd, dist, js);
const content = readFileSync(bundle);
console.log(bundle);
const { code } = transformSync(content, { minify: true });
writeFileSync(bundle, code, {});
console.log(`✨minified`);
