import { sheet } from "./style.css.js";
import { Inject } from "../../../services/di";
import { $ProfileService, ProfileService } from "../../../services/declarations";
import { ResultCard } from "../result-card";
import { B30Response, BestResultItem } from "../../../models/profile";
import { Component, HyplateElement, Show, listen, signal } from "hyplate";

const renderB30 = (response: B30Response, now: Date) => {
  const { b30, b31_39, b30Average, maxPotential, minPotential, potential, r10Average, username } = response;
  const renderBest = (best: BestResultItem) => {
    const card = new ResultCard();
    card.setChart(best.song, best.chart);
    card.setBest(best.no);
    card.setResult(best.note, best.score, best.clear);
    return card;
  };
  return (
    <div class="card" part="b30-result-card">
      <div class="mask">
        <div class="row">
          <div class="c8">
            <div class="username">
              {username} ({potential})
            </div>
            <div class="details">
              B30Avg={b30Average.toFixed(4)} R10Avg={r10Average.toFixed(4)} Ptt Range [{minPotential.toFixed(4)},{" "}
              {maxPotential.toFixed(4)}]
            </div>
          </div>
          <div class="c4">
            <div class="banner">Player Best30</div>
          </div>
        </div>
        <div class="divider"></div>
        <div class="b30">
          <div class="card-list best-1-10">{b30.slice(0, 10).map(renderBest)}</div>
          <div class="card-list best-11-20">{b30.slice(10, 20).map(renderBest)}</div>
          <div class="card-list best-21-30">{b30.slice(20, 30).map(renderBest)}</div>
        </div>
        <div class="divider"></div>
        <div class="b39">
          <div class="card-list best-31-33">{b31_39.slice(0, 3).map(renderBest)}</div>
          <div class="card-list best-34-36">{b31_39.slice(3, 6).map(renderBest)}</div>
          <div class="card-list best-37-39">{b31_39.slice(6, 9).map(renderBest)}</div>
        </div>
        <div class="footer">
          <div>
            Generated by Arcaea Toolbelt@YukiChan -RESURRECTION-{" "}
            <time datetime={now.toISOString()}>{now.toLocaleString()}</time>
          </div>
        </div>
      </div>
    </div>
  );
};

export
@Component({
  tag: "best-30",
  styles: [sheet],
})
class Best30 extends HyplateElement {
  @Inject($ProfileService)
  accessor profile!: ProfileService;

  b30 = signal<B30Response | null>(null);

  override render() {
    this.effect(() => {
      this.profile.b30().then((res) => this.b30.set(res));
      const events = listen(this as HTMLElement);
      const unsubscribe = events("dblclick", () => {
        this.requestFullscreen({
          navigationUI: "hide",
        });
      });
      return () => {
        unsubscribe();
      };
    });
    return <Show when={this.b30}>{(response) => renderB30(response, new Date(Date.now()))}</Show>;
  }
}
