# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Pull Code
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Setup Environment
        run: |
          echo "COMMIT_SHA=${{ github.sha }}" > .env
          echo "ASSETS_VENDOR=${{ secrets.ASSETS_VENDOR }}" >> .env
          echo "ASSETS_VENDOR_PROXY=${{ secrets.ASSETS_VENDOR_PROXY }}" >> .env

      - name: Build Project
        run: npm run build
      - name: Check TypeScript Types
        run: npx tsc --noEmit

      - name: Deploy Github Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: arcaea-toolbelt
          commit_message: "deploy: Deployed by Github Actions"
          jekyll: false
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
